### ISSUE TITLE
Missing Asterisk Tab

### ISSUE THREAD

**Issue by sixreeves** [noojee/Noojee-Click-for-Asterisk#5]
After users updated Firefox the Asterisk tab is gone and the Noojee in firefox quit working.

Verified this on a new install of firefox.

**Comment by bsutton** [comment]
2.0.7 restores the missing tab.
If you still have issues with njclick not working please create a new issue detailing the problem including screen shots.

**Comment by sixreeves** [comment]
When do you expect this update to reach the firefox add-ons site?

Bruce

**Comment by bsutton** [comment]
Generally its taking about 3 days at the moment.
